import "./globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Fiver Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mb-auto w-full mx-auto">{children}</body>
    </html>
  );
}
